name: absen_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.0.1 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.18.1
    image_picker: ^1.0.4
    dotted_border: ^2.1.0
    firebase_core: ^2.22.0
    firebase_auth: ^4.14.0
    email_validator: ^2.1.17
    flutter_riverpod: ^2.4.6
    cloud_firestore: ^4.13.1
    firebase_storage: ^11.5.1
    fpdart: ^1.1.0
    routemaster: ^1.0.1
    uuid: ^4.2.1
    cached_network_image: ^3.3.0
    pdf: ^3.10.6
    printing: ^5.11.1
    path_provider: ^2.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
        - assets/
